# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2e5215a5ca4c8b2d6b71da12cb3dbb80eb0fedc7334b30f6832c98088480b4c37a9537ffd5b3b575ae759427e145fb86a41e47cd1b453002cbb7898610d0418

test:
  secret_key_base: 909f8e440637c41c05bc86d28616c47f7d895a48b8a016da85c80b6551e472661ea53c9de91b1058d372addd2446a41608050ee927c8c91241e570de02dca03c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
